// https://developer.android.com/jetpack/compose/performance/stability/fix#configuration-file

// Kotlin Immutable Collections
kotlinx.collections.immutable.*

kotlin.uuid.*
kotlin.time.*

// Java Time
java.time.*

com.orchords.orchordsai.data.model.Conversation
com.orchords.orchordsai.data.model.MessageNode
com.orchords.ai.ui.UIMessage
com.orchords.ai.ui.UIMessageChoice
com.orchords.ai.ui.MessageChunk
com.orchords.ai.ui.UIMessageAnnotation
com.orchords.ai.ui.ToolApprovalState
com.orchords.ai.core.TokenUsage